config/routes.rb
Rails.application.routes.draw do
 
  root "static_pages#index"

  resources :articles, path:"aktuality", :only=>['show']

  resources :login, :only=>['create']
  get 'login', to: 'login#new'
  get 'logout', to: 'login#destroy'

  resources :reservations, only: ['create'] do
    get 'get_available_times_for_day', on: :collection
    get 'get_available_tables', on: :collection
    get 'get_reservations', on: :collection
  end

  namespace :admin do
    root 'app#index'
    resources :static_pages
    resources :article_tags, :only => [:index, :create]
    resources :articles do
      get 'tags', on: :member
    end
    resources :navs do
      resources :nav_items
    end
    resources :menu_categories do      
      resources :menu_foods, :only=>['create', 'update', 'destroy'] 
      post 'reorder', on: :collection
      post 'reorder_foods', on: :collection
    end
    resources :menu_foods, :only=>['create', 'update'] 
    resources :reservations do
      get 'get_available_times_for_day', on: :collection
      get 'get_available_tables', on: :collection
      get 'get_reservations', on: :collection
    end

    namespace :settings do      
      resources :restaurant_settings
      resources :restaurant_scheme
      resources :opening
      resources :general, :only => ['index']
    end

  end

  get '/:id' => "static_pages#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
	extend FriendlyId

	has_and_belongs_to_many :article_tag, -> { uniq }

	validates :title, presence: true
	validates :content, presence: true
	default_scope { order(:updated_at => :desc) }
	friendly_id :title, use: :slugged
	 

end

app/controllers/admin/articles_controller.rb
module Admin
	class ArticlesController < Admin::BaseController
		
		before_action :set_article, only: [:edit, :destroy, :update, :tags]

	    # GET /articles
	    def index
	      @admin_articles = Article.all
	    end

	    # GET /articles/new

	    def new
	      @admin_article = Article.new
	    end

	    # GET /articles/1/edit
	    def edit
	    end

	    # POST /articles
	    def create
				@admin_article = Article.new(article_params)
				tags = get_and_create_tags(params[:article][:tags])
				@admin_article.article_tag.destroy_all
	        if @admin_article.save && (@admin_article.article_tag << tags unless tags.nil?)
	          redirect_to admin_articles_path, notice: 'Článek byl úspěšně vytvořen.' 
	        else
	          render :new 
	        end
	    end

	    # PATCH/PUT /articles/1
			def update
					tags = get_and_create_tags(params[:article][:tags])
					
					@admin_article.article_tag.destroy_all	
	        if @admin_article.update(article_params) && (@admin_article.article_tag << tags unless tags.nil?)
	          redirect_to admin_articles_path, notice: 'Článek byl úspěšně upraven.'
	        else
	           render :edit 
	        end
	    end

	    # DELETE /articles/1
	    def destroy
	      @admin_article.destroy
	        redirect_to admin_articles_path,  notice: 'Článek byl úspešně smazán.' 
	    end


			def tags 
				if @admin_article.nil?
					render status: 400, json: {errors: "No article with such article_id"}
				else
						render json: @admin_article.article_tag.all.map{ |tag| tag.name}
				end		
			end

	    private

				def set_article
					@admin_article = Article.friendly.find(params[:id])
					rescue 
						@admin_article = nil
	      end

	        # Never trust parameters from the scary internet, only allow the white list through.

	      def article_params
	        params.require(:article).permit(:title, :content)
	      end

				def get_and_create_tags(tags)
					tags.map{|tag| ArticleTag.find_or_create_by(name: tag)}	unless tags.nil?					
				end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < BaseController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :slug, :content)
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<div class="row" ng-controller="TagsCtrl"  ng-init="init('<%= @admin_article.slug %>', '<%= form_authenticity_token %>')">
  <div class="col-md-12">
    <%= form_for([:admin, @admin_article]) do |f| %>
      <div class="form-group">
        <%= f.label :title do %>Nadpis<%end%>
        <%= f.text_field :title, :class =>"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :content do %>Obsah<%end%><br>
        <%= f.text_area :content, :class =>"form-control  tinymce"  %>
        <%= tinymce %>
      </div>

      <div class="form-group tags">
        <div class="row">
          <div class="col-md-6">
            <h4>Dostupné tagy</h4>
            <span class="tag label label-info" ng-repeat="tag in available_tags|filter:new_tag_name" ng-click="add_tag_to_artcl(tag)">
                {{tag}}
            </span>
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Filtrovat/vytvořit tagy" ng-model="new_tag_name">
                <span class="input-group-btn">
                  <button class="btn btn-success" type="button" ng-click="create_tag(new_tag_name)">Vytvořit nový</button>
                </span>
              </div><!-- /input-group -->
          </div>

          <div class="col-md-6">
              <h4>Zvolené tagy</h4>
                <span class="tag label label-info" ng-repeat="tag in article_tags" ng-click="remove_tag_to_artcl(tag)">
                    <input type="hidden" name="article[tags][]" value="{{tag}}">
                    {{tag}}
                </span>
            </div>
        </div>
      </div>
      <div class="actions form-group">
        <% unless (link_back.blank?) %>
          <%= link_to "Zpět", link_back, :class => "btn btn-info" %>
        <% end %>
        <%= f.submit :value => "Uložit", :class=>"btn btn-success" %>
      </div>      
    <% end %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<% content_for :page_heading  do %>
  <h1>Úprava aktuality <%=h @admin_article.title %></h1>
<% end %>

<%= render 'form', { :link_back => admin_articles_path }%>

app/views/admin/articles/index.html.erb
<% content_for :page_heading  do %>
  <h1>Aktuality</h1>
<% end %>
<% unless notice.blank? %>
<div class="alert alert-success alert-dismissible">  
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
  
</div>
<%end %>
<table class="table">
  <thead>
    <tr>
      <th>Název</th>
      <th>Naposledy upraveno</th>
      <th>Tagy</th>
      <th>Akce</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_articles.each do |admin_article| %>
      <tr>
        <td><%= admin_article.title %></td>
        <td><%= admin_article.updated_at.strftime("%d. %m. %Y  v %R") %></td>
        <td>
          <% admin_article.article_tag.all.each do |tag| %>
          <span class="label label-info"><%=tag.name%></span>
          <%end%>
        </td>
        <td>
          <a href="<%= url_for controller: "/articles", action: "show", id: admin_article.slug%>" class="btn btn-default" title="Zobrazit na webu">
            <i class="fa fa-eye"></i>
          </a>
          <%= link_to edit_admin_article_path(admin_article), :class=>"btn btn-warning", :title=>"Upravit" do%>
              <i class="fa fa-pencil"></i>
          <% end %>
          <%= link_to admin_article_path(admin_article), method: :delete, data: { confirm: 'Opravdu chcete smazat?' }, :class=> "btn btn-danger", :title=>"Odstranit" do %>
            <i class="fa fa-trash"></i>
          <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Nový článek', new_admin_article_path, :class=>"btn btn-success" %>

app/views/admin/articles/new.html.erb
<% content_for :page_heading  do %>
<h1>Nová aktualita</h1>
<% end %>
<%= render 'form', { :link_back => admin_articles_path }%>