config/routes.rb
Rails.application.routes.draw do
 
  root "static_pages#index"

  resources :articles, path:"aktuality", :only=>['show']

  resources :login, :only=>['create']
  get 'login', to: 'login#new'
  get 'logout', to: 'login#destroy'

  resources :reservations, only: ['create'] do
    get 'get_available_times_for_day', on: :collection
    get 'get_available_tables', on: :collection
    get 'get_reservations', on: :collection
  end

  namespace :admin do
    root 'app#index'
    resources :static_pages
    resources :article_tags, :only => [:index, :create]
    resources :articles do
      get 'tags', on: :member
    end
    resources :navs do
      resources :nav_items
    end
    resources :menu_categories do      
      resources :menu_foods, :only=>['create', 'update', 'destroy'] 
      post 'reorder', on: :collection
      post 'reorder_foods', on: :collection
    end
    resources :menu_foods, :only=>['create', 'update'] 
    resources :reservations do
      get 'get_available_times_for_day', on: :collection
      get 'get_available_tables', on: :collection
      get 'get_reservations', on: :collection
    end

    namespace :settings do      
      resources :restaurant_settings
      resources :restaurant_scheme
      resources :opening
      resources :general, :only => ['index']
    end

  end

  get '/:id' => "static_pages#show"

end

app/controllers/admin/settings/general_controller.rb
module Admin::Settings

	class GeneralController < Admin::BaseController
  		def index

  		end
	end

end

app/controllers/admin/settings/opening_controller.rb
module Admin::Settings
	class OpeningController < Admin::BaseController
		def index
			@opening_exceptions = RestaurantOpeningExceptions.where("date_when >= ?", Date.today)
			@new_opening_exception = RestaurantOpeningExceptions.new

		end
		def update
			opening_params =  {restaurant_opening_exceptions: {date_when: params[:restaurant_opening_exceptions][:date_when], opening: params[:restaurant_opening_exceptions][params[:id]][:opening_exception_hours]  }}
			@opening_exception = RestaurantOpeningExceptions.find(params[:id]).update(opening_params[:restaurant_opening_exceptions])
	        if @opening_exception
	        	flash[:success] = "Výjimka v otvírací době byla úspěšně aktualizována." 	        	 
	        else
	          	flash[:danger] = "Výjimka v otvírací době nebyla aktualizována, zkuste to prosím znovu."
	        end
			redirect_to admin_settings_opening_index_path
			
		end
		def create
			opening_params =  {restaurant_opening_exceptions: { date_when: params[:restaurant_opening_exceptions][:date_when], opening: params[:restaurant_opening_exceptions][:opening_exception_hours]  }}
			@opening_exception = RestaurantOpeningExceptions.new(opening_params[:restaurant_opening_exceptions])
	        if @opening_exception.save
	        	flash[:success] = "Výjimka v otvírací době byla úspěšně vytvořena." 	        	 
	        else
	          	flash[:danger] = "Výjimka v otvírací době nebyla vytvořena, zkuste to prosím znovu."
	        end
			redirect_to admin_settings_opening_index_path

		end
		def destroy 
			@opening_exception = RestaurantOpeningExceptions.find(params[:id]).destroy()
	        if @opening_exception
	        	flash[:success] = "Výjimka v otvírací době byla úspěšně smazána." 	        	 
	        else
	          	flash[:danger] = "Výjimka v otvírací době nebyla smazána, zkuste to prosím znovu."
	        end
	        
			redirect_to admin_settings_opening_index_path
		end
	end
end

app/controllers/admin/settings/restaurant_scheme_controller.rb
module Admin::Settings
	class RestaurantSchemeController < Admin::BaseController
		before_action :set_room, only: [:edit, :destroy, :update, :show]
		
		def index
			@tables = Table.all
			@rooms = Room.all	
		
			@new_room = Room.new
			@new_room.tables.build

		end

		def create

			@room = Room.new(room_params)
	        if @room.save
	        	flash[:success] = "Místnost byla úspěšně vytvořena." 	        	 
	        else
	          	flash[:danger] = "Místnost nebyla vytvořena, zkuste to prosím znovu."
	        end
	        redirect_to admin_settings_restaurant_scheme_index_path

		end

		def update

			@room.update(room_params)
	        if @room.save
	        	flash[:success] = "Místnost byla úspěšně změněna." 	        	 
	        else
	          	flash[:danger] = "Místnost nebyla vytvořena, zkuste to prosím znovu."
	        end
	        redirect_to admin_settings_restaurant_scheme_index_path
		end
		def destroy
			if @room.destroy
				flash[:success] = "Místnost byla úspěšně smazána." 
			else
				flash[:danger] = "Místnost nebyla smazána, zkuste to prosím znovu." 
			end
			redirect_to admin_settings_restaurant_scheme_index_path
		end


		private


		def room_params
	    	params.require(:room).permit(:name, :smoking,  tables_attributes: [:id, :number, :persons, :_destroy])
	    end
		
		def set_room
	        @room = Room.find(params[:id])
	    end
	end
end

app/controllers/admin/settings/restaurant_settings_controller.rb
module Admin::Settings
	class RestaurantSettingsController < Admin::BaseController
		
		def update
			a = settings_params

			a.merge!({opening_hours: params[:restaurant_settings][:opening_hours]}) unless params[:restaurant_settings][:opening_hours].nil?
			a.merge!({general_settings: params[:restaurant_settings][:general_settings]}) unless params[:restaurant_settings][:general_settings].nil?

			@restaurant_settings.update(a)
	        if @restaurant_settings.save
	        	flash[:success] = "Nastavení bylo úspěšně změněno." 	        	 
	        else
	          	flash[:danger] = "Nastavení nebyla změněno, zkuste to prosím znovu."
	        end

	        redirect_to request.referrer
		end

		private


		def settings_params
	    	params.require(:restaurant_settings).permit(:restaurant_scheme, :delete_image, :opening_hours)
	    end
		
	
	end
end

app/helpers/admin/settings/general_helper.rb
module Admin::Settings::GeneralHelper
end

app/helpers/admin/settings/opening_helper.rb
module Admin::Settings::OpeningHelper
end

app/helpers/admin/settings/reservations_helper.rb
module Admin::Settings::ReservationsHelper
end

app/helpers/admin/settings/restaurant_settings_helper.rb
module Admin::Settings::RestaurantSettingsHelper
end

app/views/admin/settings/opening/index.html.erb
<% content_for :page_heading  do %>
  <h1>Nastavení restaurace - otevírací doba</h1>
<% end %>
<div class="row">
	<div class="col-md-12">
		<div class="row">
	      <div class="col-md-12">
	        <%= render "admin/shared/admin_messages"%>
	      </div>
	    </div>
	</div>
</div>


<div class="row restaurant-opening" ng-controller="OpeningCtrl">
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div class="panel panel-default">
				    <div class="panel-heading">
				    	<div class="panel-heading-content"><h2 class="panel-title">Standartní otevírací doba</h2></div>
				    </div>
				    <%= form_for(@restaurant_settings, :url=> url_for(:controller =>'restaurant_settings', :action=>'update', :id=> 1), :html=> {:class=>'form'}) do |f| %>						
					  	<div class="panel-body">
					  			<div class="row">
							    	
									<%
										days = {mon: "Pondělí", tue: "Úterý", wed: "Středa", thu: "Čtvrtek", fri: "Pátek", sat: "Sobota", sun: "Neděle"}
										@restaurant_settings[:opening_hours] ||=  {}
										days.keys.each do | key |
											@restaurant_settings[:opening_hours][:"#{key}"]||= {from: nil, to: nil}
									%>
									<div class="col-md-6">
										<div class="day-wrapper">
											<div class="time-range-wrapper"  ng-init="connectFromTo('restaurant_settings[opening_hours][<%=key%>][from]', 'restaurant_settings[opening_hours][<%=key%>][to]')">								
												<table class="table table-bordered">
													<tr class="table-heading"><th colspan="3"><%= days[key]%>:</th></tr>
													<tr class="table-subheading"><th>Od</th><th>Do</th><th>Zavřeno</th></tr>
													<tr>
														<td ng-hide="OpeningResetInput['<%=key%>']">
															<%= render "shared/widgets/time_input", key: "restaurant_settings[opening_hours][#{key}][from]", field:@restaurant_settings[:opening_hours][:"#{key}"][:from] %>
														</td ng-hide="OpeningResetInput['<%=key%>']">
														<td  ng-hide="OpeningResetInput['<%=key%>']">
															<%= render "shared/widgets/time_input", key: "restaurant_settings[opening_hours][#{key}][to]", field:@restaurant_settings[:opening_hours][:"#{key}"][:to] %>
														</td>
														<td colspan="2"  ng-show="OpeningResetInput['<%=key%>']"><strong>Zavřeno</strong></td> 
														<td>
															<input  id = "checkbox-10-<%=key%>" type="checkbox" class="form-control" name = "restaurant_settings[opening_hours][<%=key%>][closed]"  ng-init="OpeningResetInput['<%=key%>'] = <%= (@restaurant_settings[:opening_hours][:"#{key}"][:closed] == 'on')? 'true': 'false'%>  " ng-model="OpeningResetInput['<%=key%>']">
															<label for="checkbox-10-<%=key%>" ></label>
														</td>
													</tr>
												</table>				
											</div>
										</div>
									</div>
									<% end	%>					
								</div>	   
				     	</div>
				     	<div class="panel-footer">
							<%= button_tag "Uložit otevírací doby", :value => "", :class=>"btn btn-success", :title=>"Uložit otevírací doby"%>	
						</div>	
					 <% end %>			
				</div>
		 	</div>
		</div>
		



		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div class="panel panel-default">
				    <div class="panel-heading">
				    	<div class="panel-heading-content"><h2 class="panel-title">Výjimky v otevírací době</h2></div>   
				    </div>
				  	<div class="panel-body">
				  		
				  		<div class="panel-group opening-panels-container" id="accordion" role="tablist" aria-multiselectable="true">
							<%= form_for(@new_opening_exception, :url=> url_for(:controller =>'opening', :action=>'create'), :html=> {:class=>'form'}) do |f| %>  
							      
								<div class="panel panel-default opening-panel">  

									<div class="panel-heading" role="tab" id="headingOne">
								        	<div class="panel-heading-content">Přidat den s jinou otevírací dobou</div>              
								          	<span class="icos-right pull-right info">
								            	<a title="Přidat výjimku" class="ico ico-new" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0"   ></a> 
								             
								          	</span>
								          	<span class="icos-right pull-right edit">
								            	<%= button_tag "", :value => "", :class=>"ico ico-save", :title=>"Uložit výjimku"%>
								            	<a title="Zrušit" class="ico ico-back" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0"  ></a>  
								           </span>
								      	</div>
									    <div id="collapse0" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading0">
									    	<div class="panel-body">						          
									            <div class="row">
									              	<div class="col-md-12">
														<div class="day-wrapper">
															<div class="time-range-wrapper"  ng-init="connectFromTo('restaurant_opening_exceptions[opening_exception_hours][from]', 'restaurant_opening_exceptions[opening_exception_hours][to]')">								
																<table class="table table-bordered">
																	<tr class="table-subheading"><th>Datum</th><th>Od</th><th>Do</th><th>Zavřeno</th></tr>
																	<tr>
																		<td><%= f.text_field :date_when, :class =>"form-control datepicker" , "ng-model" => "form.title" %></td>
																		<td ng-hide="OpeningResetInput['opening_exception_hours']">
																			<%= render "shared/widgets/time_input", key: "restaurant_opening_exceptions[opening_exception_hours][from]" %>
																		</td ng-hide="OpeningResetInput['opening_exception_hours']">
																		<td  ng-hide="OpeningResetInput['opening_exception_hours']">
																			<%= render "shared/widgets/time_input", key: "restaurant_opening_exceptions[opening_exception_hours][to]" %>
																		</td>
																		<td colspan="2"  ng-show="OpeningResetInput['opening_exception_hours']"><strong>Zavřeno</strong></td> 
																		<td>
																			<input id = "checkbox-10-new-exception" type="checkbox" class="form-control" name = "restaurant_opening_exceptions[opening_exception_hours][closed]"  ng-model="OpeningResetInput['opening_exception_hours']">
																			<label for="checkbox-10-new-exception" ></label>
																		</td>
																	</tr>
																</table>				
															</div>
														</div>
									              	</div>
									            </div>             
									        </div>
									    </div>
								   
							    </div>
							<% end %>
						</div>
	


























<div class="panel-group opening-panels-container" id="accordion" role="tablist" aria-multiselectable="true">
<% @opening_exceptions.each_with_index  do |opening_exception, i|  %>
	<div class="panel panel-default  opening-panel">  
		
		<%= form_for(opening_exception, :url=> url_for(:controller =>'opening', :action=>'update', id: opening_exception.id), :html=> {:class=>'form'}) do |f| %>  
	      	<div class="panel-heading" role="tab">
	        	<div class="panel-heading-content">
	        		<strong>{{restaurant_opening_exceptions['<%=opening_exception.id%>']['date_when']}}</strong>:
	        		<span  ng-hide="restaurant_opening_exceptions['<%=opening_exception.id%>'][opening_exception_hours][closed]">
	        			Otevřeno
						{{print_nice_time(timePicker['restaurant_opening_exceptions[<%=opening_exception.id%>][opening_exception_hours][from]'])}}
						-
						{{print_nice_time(timePicker['restaurant_opening_exceptions[<%=opening_exception.id%>][opening_exception_hours][to]'])}}

        			</span>
					<span  ng-show="restaurant_opening_exceptions['<%=opening_exception.id%>'][opening_exception_hours][closed]">Zavřeno</span>
	        	</div>              
	          	<span class="icos-right pull-right info">
	            		<a title="Upravit výjimku" class="ico ico-edit" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= i+1 %>" aria-expanded="true" aria-controls="collapse<%= i+1 %>" ng-click="set_panel_to_default('<%=opening_exception.id%>')"  ></a> 
                    	<%= link_to "", admin_settings_opening_path(opening_exception.id), method: :delete, data: { confirm: 'Opravdu chcete smazat?' }, :title=>"Odstranit", :class=>"ico ico-destroy"%> 
	             
	          	</span>
	          	<span class="icos-right pull-right edit">
	            	<%= button_tag "", :value => "", :class=>"ico ico-save", :title=>"Uložit výjimku"%>
	            	<a title="Zrušit" class="ico ico-back" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=i+1%>" aria-expanded="true" aria-controls="collapse<%=i+1%>", ng-click="reset_panel_to_default('<%=opening_exception.id%>')" ></a>  
	           </span>
	      	</div>
		    <div id="collapse<%=i+1%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%=i+1%>">
		    	<div class="panel-body">						          
		            <div class="row">
		              	<div class="col-md-12">
							<div class="day-wrapper">
								<div class="time-range-wrapper"  ng-init="connectFromTo('restaurant_opening_exceptions[<%=opening_exception.id%>][opening_exception_hours][from]', 'restaurant_opening_exceptions[<%=opening_exception.id%>][opening_exception_hours][to]')">								
									<table class="table table-bordered">
										<tr class="table-subheading"><th>Datum</th><th>Od</th><th>Do</th><th>Zavřeno</th></tr>
										<tr>
											<td><%= f.text_field :date_when, {:class =>"form-control datepicker", :id=>nil, :'ng-model'=>"restaurant_opening_exceptions['#{opening_exception.id}']['date_when']", :'ng-init' => "restaurant_opening_exceptions['#{opening_exception.id}']['date_when'] = \" #{opening_exception[:date_when].strftime('%d.%m.%Y')}\" " } %></td>
											<td ng-hide="restaurant_opening_exceptions['<%=opening_exception.id%>'][opening_exception_hours][closed]">
												<%= render "shared/widgets/time_input", key: "restaurant_opening_exceptions[#{opening_exception.id}][opening_exception_hours][from]", field: opening_exception[:opening][:from] %>
											</td>
											<td  ng-hide="restaurant_opening_exceptions['<%=opening_exception.id%>'][opening_exception_hours][closed]">
												<%= render "shared/widgets/time_input", key: "restaurant_opening_exceptions[#{opening_exception.id}][opening_exception_hours][to]", field: opening_exception[:opening][:to] %>
											</td>
											<td colspan="2"  ng-show="restaurant_opening_exceptions['<%=opening_exception.id%>'][opening_exception_hours][closed]"><strong>Zavřeno</strong></td> 
											<td>
												<input id = "checkbox-10-new-exception-<%=i%>" type="checkbox" class="form-control" name = "restaurant_opening_exceptions['<%=opening_exception.id%>'][opening_exception_hours][closed]"  ng-model="restaurant_opening_exceptions['<%=opening_exception.id%>'][opening_exception_hours][closed]"  ng-init="restaurant_opening_exceptions['<%=opening_exception.id%>'][opening_exception_hours][closed] = <%= (opening_exception[:opening][:closed] == 'on')? 'true': 'false'%>  ">
												<label for="checkbox-10-new-exception-<%=i%>" ></label>
											</td>
										</tr>
									</table>				
								</div>
							</div>
		              	</div>
		            </div>             
		        </div>
		    </div>
	    <% end %>
    </div>
<% end %>	
</div>























				  		

						</div>







			     	</div>			
				</div>
		 	</div>
		</div>






	</div>
  
</div>