config/routes.rb
Rails.application.routes.draw do
 
  root "static_pages#index"

  resources :articles, path:"aktuality", :only=>['show']

  resources :login, :only=>['create']
  get 'login', to: 'login#new'
  get 'logout', to: 'login#destroy'

  resources :reservations, only: ['create'] do
    get 'get_available_times_for_day', on: :collection
    get 'get_available_tables', on: :collection
    get 'get_reservations', on: :collection
  end

  namespace :admin do
    root 'app#index'
    resources :static_pages
    resources :article_tags, :only => [:index, :create]
    resources :articles do
      get 'tags', on: :member
    end
    resources :navs do
      resources :nav_items
    end
    resources :menu_categories do      
      resources :menu_foods, :only=>['create', 'update', 'destroy'] 
      post 'reorder', on: :collection
      post 'reorder_foods', on: :collection
    end
    resources :menu_foods, :only=>['create', 'update'] 
    resources :reservations do
      get 'get_available_times_for_day', on: :collection
      get 'get_available_tables', on: :collection
      get 'get_reservations', on: :collection
    end

    namespace :settings do      
      resources :restaurant_settings
      resources :restaurant_scheme
      resources :opening
      resources :general, :only => ['index']
    end

  end

  get '/:id' => "static_pages#show"

end

app/controllers/admin/settings/general_controller.rb
module Admin::Settings

	class GeneralController < Admin::BaseController
  		def index

  		end
	end

end

app/controllers/admin/settings/opening_controller.rb
module Admin::Settings
	class OpeningController < Admin::BaseController
		def index
			@opening_exceptions = RestaurantOpeningExceptions.where("date_when >= ?", Date.today)
			@new_opening_exception = RestaurantOpeningExceptions.new

		end
		def update
			opening_params =  {restaurant_opening_exceptions: {date_when: params[:restaurant_opening_exceptions][:date_when], opening: params[:restaurant_opening_exceptions][params[:id]][:opening_exception_hours]  }}
			@opening_exception = RestaurantOpeningExceptions.find(params[:id]).update(opening_params[:restaurant_opening_exceptions])
	        if @opening_exception
	        	flash[:success] = "Výjimka v otvírací době byla úspěšně aktualizována." 	        	 
	        else
	          	flash[:danger] = "Výjimka v otvírací době nebyla aktualizována, zkuste to prosím znovu."
	        end
			redirect_to admin_settings_opening_index_path
			
		end
		def create
			opening_params =  {restaurant_opening_exceptions: { date_when: params[:restaurant_opening_exceptions][:date_when], opening: params[:restaurant_opening_exceptions][:opening_exception_hours]  }}
			@opening_exception = RestaurantOpeningExceptions.new(opening_params[:restaurant_opening_exceptions])
	        if @opening_exception.save
	        	flash[:success] = "Výjimka v otvírací době byla úspěšně vytvořena." 	        	 
	        else
	          	flash[:danger] = "Výjimka v otvírací době nebyla vytvořena, zkuste to prosím znovu."
	        end
			redirect_to admin_settings_opening_index_path

		end
		def destroy 
			@opening_exception = RestaurantOpeningExceptions.find(params[:id]).destroy()
	        if @opening_exception
	        	flash[:success] = "Výjimka v otvírací době byla úspěšně smazána." 	        	 
	        else
	          	flash[:danger] = "Výjimka v otvírací době nebyla smazána, zkuste to prosím znovu."
	        end
	        
			redirect_to admin_settings_opening_index_path
		end
	end
end

app/controllers/admin/settings/restaurant_scheme_controller.rb
module Admin::Settings
	class RestaurantSchemeController < Admin::BaseController
		before_action :set_room, only: [:edit, :destroy, :update, :show]
		
		def index
			@tables = Table.all
			@rooms = Room.all	
		
			@new_room = Room.new
			@new_room.tables.build

		end

		def create

			@room = Room.new(room_params)
	        if @room.save
	        	flash[:success] = "Místnost byla úspěšně vytvořena." 	        	 
	        else
	          	flash[:danger] = "Místnost nebyla vytvořena, zkuste to prosím znovu."
	        end
	        redirect_to admin_settings_restaurant_scheme_index_path

		end

		def update

			@room.update(room_params)
	        if @room.save
	        	flash[:success] = "Místnost byla úspěšně změněna." 	        	 
	        else
	          	flash[:danger] = "Místnost nebyla vytvořena, zkuste to prosím znovu."
	        end
	        redirect_to admin_settings_restaurant_scheme_index_path
		end
		def destroy
			if @room.destroy
				flash[:success] = "Místnost byla úspěšně smazána." 
			else
				flash[:danger] = "Místnost nebyla smazána, zkuste to prosím znovu." 
			end
			redirect_to admin_settings_restaurant_scheme_index_path
		end


		private


		def room_params
	    	params.require(:room).permit(:name, :smoking,  tables_attributes: [:id, :number, :persons, :_destroy])
	    end
		
		def set_room
	        @room = Room.find(params[:id])
	    end
	end
end

app/controllers/admin/settings/restaurant_settings_controller.rb
module Admin::Settings
	class RestaurantSettingsController < Admin::BaseController
		
		def update
			a = settings_params

			a.merge!({opening_hours: params[:restaurant_settings][:opening_hours]}) unless params[:restaurant_settings][:opening_hours].nil?
			a.merge!({general_settings: params[:restaurant_settings][:general_settings]}) unless params[:restaurant_settings][:general_settings].nil?

			@restaurant_settings.update(a)
	        if @restaurant_settings.save
	        	flash[:success] = "Nastavení bylo úspěšně změněno." 	        	 
	        else
	          	flash[:danger] = "Nastavení nebyla změněno, zkuste to prosím znovu."
	        end

	        redirect_to request.referrer
		end

		private


		def settings_params
	    	params.require(:restaurant_settings).permit(:restaurant_scheme, :delete_image, :opening_hours)
	    end
		
	
	end
end

app/helpers/admin/settings/general_helper.rb
module Admin::Settings::GeneralHelper
end

app/helpers/admin/settings/opening_helper.rb
module Admin::Settings::OpeningHelper
end

app/helpers/admin/settings/reservations_helper.rb
module Admin::Settings::ReservationsHelper
end

app/helpers/admin/settings/restaurant_settings_helper.rb
module Admin::Settings::RestaurantSettingsHelper
end

app/views/admin/settings/restaurant_scheme/index.html.erb
<% content_for :page_heading  do %>
  <h1>Nastavení restaurace - struktura restaurace</h1>
<% end %>

<div class="row settings-rooms">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-12">
        <%= render "admin/shared/admin_messages"%>
      </div>
    </div>


    <div class="row restaurant-scheme">
      <div class="col-md-10 col-md-offset-1">
        <%= form_for(@restaurant_settings, :url=> url_for(:controller =>'restaurant_settings', :action=>'update', :id=> 1), :html=> {:class=>'form'}) do |f| %>

            <%= render 'admin/shared/img_upload/img_upload', { :form => f, :image => @restaurant_settings.restaurant_scheme, :image_input_name => 'restaurant_scheme', :has_form_buttons=>true } %>

        <% end %>
      </div>
    </div>




    <div class="row">
      <div class="col-md-12">






<!-- new room -->
<div class="room-panels-container editing-panels-container"> 
  <%= nested_form_for(@new_room, :url=> url_for(:controller =>'restaurant_scheme', :action=>'create'), :html=> {:class=>'form'}) do |f| %>
    <div class="panel panel-default room new-room editing-panel" id="new-room">    
      <div class="panel-heading" role="tab" id="headingOne">
        <div class="panel-heading-content">Nová místnost</div>              
          <span class="icos-right pull-right info">
            <a title="Přidat místnost" class="ico ico-new" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0"   ></a> 
             
          </span>
          <span class="icos-right pull-right edit">
            <%= button_tag "", :value => "", :class=>"ico ico-save", :title=>"Uložit místnost"%>
            <a title="Zrušit" class="ico ico-back" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0"  ></a>  
           </span>
      </div>
      <div id="collapse0" class="panel-collapse collapse <%= 'in' if @rooms.nil? %> " role="tabpanel" aria-labelledby="heading0">
        <div class="panel-body">
          
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label :name  do %>Název<%end%>
                  <%= f.text_field :name, :class =>"form-control", :id=>"new_room_form_name", :placeholder => "Název místnosti"%>
                </div>
              </div>
              <div class="col-md-6">


                  <div class="form-group">
                    <label>Kuřácká</label><br>
                      <%= f.check_box :smoking, :id=>"checkbox-10-smoking-new", :placeholder => "Kuřácká"%>
                    <label for="checkbox-10-smoking-new"></label>
                  </div>      
              </div>
            </div> 
            <div class="row">
              <div class="col-md-12">   
                <div class="panel panel-default">
                   <div class="panel-heading"><div class="panel-heading-content">Stoly v místnosti</div></div>
                   <div class="panel-body">
                     <div class="row">
                       <div class="col-md-12">  


                        <div class="room-tables-list" id="room_0-tables-list">
                          <%= f.fields_for :tables do |table_f| %>
                            <div class="room-table">
                              <div class="room-table-group">
                                <div class="room-table-part">
                                  <div class="form-group">
                                    <%= table_f.label :number, :title => "Číslo stolu", :for=>"room_tables_attributes_room_0_table_#{table_f.index}_number"  do %><i class="fa fa-tag fa-lg"></i><%end%>
                                    <%= table_f.number_field :number, :class=>'form-control room-table-number', :id=>"room_tables_attributes_room_0_table_#{table_f.index}_number" %>
                                  </div>
                                </div>
                                <div class="room-table-part">
                                  <div class="form-group">
                                    <%= table_f.label :persons, :title => "Počet osob", :for=>"room_tables_attributes_room_0_table_#{table_f.index}_persons" do %><i class="fa fa-user fa-lg"></i><%end%>
                                    <%= table_f.number_field :persons, :class=>'form-control room-table-last-input', :id=>"room_tables_attributes_room_0_table_#{table_f.index}_persons" %>
                                  </div>
                                </div>
                              </div>
                              <div class="room-table-group actions">
                                <div class="table-part">
                                  <%= table_f.link_to_remove "",  :class=>"ico ico-destroy", :tabindex=>"-1" %>
                                  <%= link_to "",  "", :class=>"ico ico-edit", :tabindex=>"-1" %>
                                </div>     
                              </div>    
                            </div>
                          <% end %>              
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">  
                          <div class="room-table new-room-table">
                              <div class="room-table-group">
                                  <%= f.link_to_add "", :tables, :class=>"ico ico-new", :data => { :target => "#room_0-tables-list" }, :title=>"Nový stůl" %>
                              </div>
                          </div> 
                      </div>
                    </div>            
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>






















<!-- list rooms -->
<div class="panel-group room-panels-container editing-panels-container"> 
<% @rooms.each_with_index do |room, i| %>

    <div class="panel panel-default room editing-panel" id="room_<%=i%>">   

      <%= nested_form_for(room, :url=> url_for(:controller =>'restaurant_scheme', :action=>'update', :id=>room.id), :html=> {:class=>'form'}) do |f| %> 
      <div class="panel-heading" role="tab" id="headingOne">




        <div class="panel-heading-content"><%= room.name %></div>    
          <!-- normal display -->          
          <span class="icos-right pull-right info">
            <a title="Upravit místnost" class="ico ico-edit" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= i+1 %>" aria-expanded="true" aria-controls="collapse<%= i+1 %>"   ></a> 
            <%= link_to "",admin_settings_restaurant_scheme_path(room.id), method: :delete, data: { confirm: 'Opravdu chcete smazat?' }, :title=>"Odstranit", :class=>"ico ico-destroy" %>   
          </span>
          <!-- edit display -->
          <span class="icos-right pull-right edit">
            <%= button_tag "", :value => "", :class=>"ico ico-save", :title=>"Uložit"%>
            <a title="Zrušit úpravy" class="ico ico-back" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= i+1 %>" aria-expanded="true" aria-controls="collapse<%= i+1 %>"  ></a>  
            <%= link_to "",admin_settings_restaurant_scheme_path(room.id), method: :delete, data: { confirm: 'Opravdu chcete smazat?' }, :title=>"Odstranit", :class=>"ico ico-destroy" %>   
          </span>


      </div>
      <div id="collapse<%= i+1 %>" class="panel-collapse collapse <%= 'in' if @rooms.nil? %> " role="tabpanel" aria-labelledby="heading<%= i+1 %>">
        <div class="panel-body">
          
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label :name  do %>Název<%end%>
                  <%= f.text_field :name, :class =>"form-control", :id=>"new_room_form_name", :placeholder => "Název místnosti"%>
                </div>
              </div>
              <div class="col-md-6">
                 <div class="form-group">
                    <label>Kuřácká</label><br>
                      <%= f.check_box :smoking, :id=>"checkbox-10-smoking-#{i}", :placeholder => "Kuřácká"%>
                    <label for="checkbox-10-smoking-<%=i%>"></label>
                  </div>      
              </div>
            </div> 
        
            <div class="row">
              <div class="col-md-12">   
                <div class="panel panel-default">
                   <div class="panel-heading"><div class="panel-heading-content">Stoly v místnosti</div></div>
                   <div class="panel-body">
                     <div class="row">
                       <div class="col-md-12">  
                        <div class="room-tables-list" id="room_<%= i+1 %>-tables-list">
                          <%= f.fields_for :tables do |table_f| %>
                            <div class="room-table">
                              <div class="room-table-group">
                                <div class="room-table-part">
                                  <div class="form-group">
                                    <%= table_f.label :number, :title => "Číslo stolu", :for=>"room_tables_attributes_room_#{i+1}_table_#{table_f.index}_number"  do %><i class="fa fa-tag fa-lg"></i><%end%>
                                    <%= table_f.number_field :number, :class=>'form-control room-table-number', :id=>"room_tables_attributes_room_#{i+1}_table_#{table_f.index}_number" %>
                                  </div>
                                </div>
                                <div class="room-table-part">
                                  <div class="form-group">
                                    <%= table_f.label :persons, :title => "Počet osob", :for=>"room_tables_attributes_room_#{i+1}_table_#{table_f.index}_persons" do %><i class="fa fa-user fa-lg"></i><%end%>
                                    <%= table_f.number_field :persons, :class=>'form-control room-table-last-input', :id=>"room_tables_attributes_room_#{i+1}_table_#{table_f.index}_persons" %>
                                  </div>
                                </div>
                              </div>
                              <div class="room-table-group actions">
                                <div class="table-part">
                                  <%= table_f.link_to_remove "",  :class=>"ico ico-destroy", :tabindex=>"-1" %>
                                  <%= link_to "",  "#", :class=>"ico ico-edit", :tabindex=>"-1" %>
                                </div>     
                              </div>    
                            </div>
                          <% end %>              
                        </div>

                       </div>
                     </div>
                      <div class="row">
                        <div class="col-md-12">  
                            <div class="room-table new-room-table">
                                <div class="room-table-group">
                                    <%= f.link_to_add "", :tables, :class=>"ico ico-new", :data => { :target => "#room_#{i+1}-tables-list" }, :title=>"Nový stůl" %>
                                </div>
                            </div> 
                        </div>
                      </div>  
                   </div>
                 </div>
                
              </div>
            </div>
                     
          </div>
      </div>

  <% end %>
    </div>

<% end %>

</div>

































    </div>
</div>